### ISSUE TITLE
occ doesn't work after upgrade to v2.0.0

### ISSUE THREAD

**Issue by PhantomPhreak** [nextcloud/groupfolders#242]
After upgrading to groupfolders v.2.0.0 i have this error while running occ commands
```
# sudo -u www-data php occ 
The process control (PCNTL) extensions are required in case you want to interrupt long running commands - see http://php.net/manual/en/book.pcntl.php
An unhandled exception has been thrown:
ArgumentCountError: Too few arguments to function OCA\GroupFolders\Command\ExpireGroupVersions::__construct(), 0 passed in /var/www/lib/private/Console/Application.php on line 222 and exactly 1 expected in /var/www/apps/groupfolders/lib/Command/ExpireGroupVersions.php:34
Stack trace:
#0 /var/www/lib/private/Console/Application.php(222): OCA\GroupFolders\Command\ExpireGroupVersions->__construct()
#1 /var/www/lib/private/Console/Application.php(134): OC\Console\Application->loadCommandsFromInfoXml(Array)
#2 /var/www/console.php(95): OC\Console\Application->loadCommands(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /var/www/occ(11): require_once('/var/www/consol...')
#4 {main}
```

Nextcloud v14.0.4
php7.1

**Comment by TP75** [comment]
one may have a look at #240 and #241

**Comment by JanUrlaub** [comment]
I have also this issue.
It maybe helps to find the core issue, that to enable the "Versions" App cause the error of #240

**Comment by PhantomPhreak** [comment]
> I have also this issue.
> It maybe helps to find the core issue, that to enable the "Versions" App cause the error of #240

Yeah, thanks. i've just enabled "Versions" App and had the same issue as in #240
So, this ussiue can be closet as duplicate.

Thanks again!
