### ISSUE TITLE
After ugrade get error

### ISSUE THREAD

**Issue by Raito00** [nextcloud/groupfolders#3031]
```
ArgumentCountError
Too few arguments to function OCA\GroupFolders\Versions\VersionsBackend::__construct(), 7 passed in /var/www/nextcloud/apps/groupfolders/lib/AppInfo/Application.php on line 160 and exactly 8 expected
Could not boot files_trashbin: Too few arguments to function OCA\GroupFolders\Versions\VersionsBackend::__construct(), 7 passed in /var/www/nextcloud/apps/groupfolders/lib/AppInfo/Application.php on line 160 and exactly 8 expected
```

![image](https://github.com/nextcloud/groupfolders/assets/25778187/75fa3bf9-f436-4c5d-b660-6374ffb0491a)

Group Folders: Version 17.0.1
Nextcloud: 29.0.3

**Comment by steamrick** [comment]
Sadly, I can confirm getting the same error after upgrading from 28.0.7 to 29.0.3.

**Comment by joshtrichards** [comment]
There are eight parameters. However there were not in the prior version. This sounds like a PHP caching issue. Please restart your web server (if using mod_php) or FPM (if using).

**Comment by joshtrichards** [comment]
Duplicate of #2971
