### ISSUE TITLE
Group folder do not display extended rights after update to 25.0.5

### ISSUE THREAD

**Issue by Staanly1988** [nextcloud/groupfolders#2340]
### Steps to reproduce
1. when I add extended rights to group folders the added member is not shown

### Expected behaviour
added member should be displayed
### Actual behaviour
added member is not shown
### Server configuration
qemu vm 
4 cores
16gb ram
**Operating system:**
Linux 5.15.0-70-generic x86_64
Ubuntu 22.04.1 LTS
**Web server:**
Apache/2.4.52
**Database:**
MYSQL 10.6.12
**PHP version:**
PHP 8.1
**Nextcloud version:** (see Nextcloud admin page)
25.0.5
**Group folders version:**
13.1.2
**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated from 25.0.3
**Where did you install Nextcloud from:**
Installed from nextcloud official repository
https://download.nextcloud.com/server/releases/latest.zip

### Client configuration
**Browser:**
Chrome 111.0.5563.149
**Operating system:**
Windows 10

</details>

![image](https://user-images.githubusercontent.com/12234510/235358593-4d0485eb-e71e-4ee6-9b9a-704691b1c95d.png)

### Log
```
ArgumentCountError: Too few arguments to function OCA\GroupFolders\Trash\TrashBackend::__construct(), 6 passed in /var/www/nextcloud/apps/groupfolders/lib/AppInfo/Application.php on line 111 and exactly 7 expected
ArgumentCountError: Too few arguments to function OCA\GroupFolders\Trash\TrashBackend::__construct(), 6 passed in /var/www/nextcloud/apps/groupfolders/lib/AppInfo/Application.php on line 111 and exactly 7 expected
/var/www/nextcloud/apps/groupfolders/lib/AppInfo/Application.php - line 111:

OCA\GroupFolders\Trash\TrashBackend->__construct()

/var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php - line 171:

OCA\GroupFolders\AppInfo\Application->OCA\GroupFolders\AppInfo\{closure}("*** sensiti ... *")

/var/www/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php - line 122:

OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}("*** sensiti ... *")

/var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php - line 138:

Pimple\Container->offsetGet()

/var/www/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php - line 487:

OC\AppFramework\Utility\SimpleContainer->query()

/var/www/nextcloud/lib/private/ServerContainer.php - line 155:

OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback()

/var/www/nextcloud/apps/files_trashbin/lib/AppInfo/Application.php - line 95:

OC\ServerContainer->query()

/var/www/nextcloud/lib/private/AppFramework/Bootstrap/FunctionInjector.php - line 66:

OCA\Files_Trashbin\AppInfo\Application->registerTrashBackends()

/var/www/nextcloud/lib/private/AppFramework/Bootstrap/BootContext.php - line 50:

OC\AppFramework\Bootstrap\FunctionInjector->injectFn()

/var/www/nextcloud/apps/files_trashbin/lib/AppInfo/Application.php - line 61:

OC\AppFramework\Bootstrap\BootContext->injectFn()

/var/www/nextcloud/lib/private/AppFramework/Bootstrap/Coordinator.php - line 200:

OCA\Files_Trashbin\AppInfo\Application->boot()

/var/www/nextcloud/lib/private/legacy/OC_App.php - line 213:

OC\AppFramework\Bootstrap\Coordinator->bootApp()

/var/www/nextcloud/lib/private/legacy/OC_App.php - line 141:

OC_App::loadApp()

/var/www/nextcloud/apps/dav/lib/AppInfo/Application.php - line 205:

OC_App::loadApps()

/var/www/nextcloud/lib/private/AppFramework/Bootstrap/Coordinator.php - line 200:

OCA\DAV\AppInfo\Application->boot()

/var/www/nextcloud/lib/private/legacy/OC_App.php - line 213:

OC\AppFramework\Bootstrap\Coordinator->bootApp()

/var/www/nextcloud/lib/private/legacy/OC_App.php - line 141:

OC_App::loadApp()

/var/www/nextcloud/ocs/v1.php - line 58:

OC_App::loadApps()

/var/www/nextcloud/ocs/v2.php - line 23:

require_once("/var/www/nextcloud/ocs/v1.php")
```

</details>

**Comment by solracsf** [comment]
Does your files on disk match these contents?
**If yes**, does retart PHP help?

https://github.com/nextcloud/groupfolders/blob/c306926f11bb475b0ab9bbc673536f36e8180a23/lib/Trash/TrashBackend.php#L52-L66

https://github.com/nextcloud/groupfolders/blob/c306926f11bb475b0ab9bbc673536f36e8180a23/lib/AppInfo/Application.php#L104-L118

**Comment by solracsf** [comment]
Closing due to lack of feedback.
